### ISSUE TITLE
How about hosting on GitHub Pages?

### ISSUE THREAD

**Issue by andy0130tw** [ByronHsu/AAG-Visualizer#1]
I just found this elegant project in the Facebook group of DSnP. The project is really an awesome try on visualizing the aag files! However, I noticed that you host files on Heroku. Since all files are static, I think it is wise to move them to [GitHub Pages](https://pages.github.com/) instead. To do so, you just need to

1. Create a new branch (`git checkout --orphan gh-pages` is preferred).
2. Move all static files (i.e. `public/*`) to the root directory of the repository.
3. Fix some paths like those pointing to scripts. Commit. Push.
4. Configure in the option page on GitHub.

I clone the project [here](https://github.com/andy0130tw/AAG-Visualizer) and the resulted page is [here](https://andy0130tw.github.io/AAG-Visualizer/). I currently see no issues on using this web app. If you find it useful, you can copy the entire `gh-pages` branch of mine. Thanks.

**Comment by ByronHsu** [comment]
Thanks guy. : )
It is super fast and convenient.
I have changed the homepage to [here](https://byronhsu.github.io/AAG-Visualizer/) now
Try it!
