### ISSUE TITLE
viz.js too big

### ISSUE THREAD

**Issue by ByronHsu** [ByronHsu/AAG-Visualizer#3]
The package viz.js is too big, causing the web page loaded slowly.

**Comment by hsiaoyi0504** [comment]
It looks like you can get lite version from release page. https://github.com/mdaines/viz.js/releases.

Description is [here](https://github.com/mdaines/viz.js#lite-version).

**Comment by ByronHsu** [comment]
But is still 1.62MB.
I wonder that can I minimize its size by some tricks like tree-shaking or uglify?

**Comment by hsiaoyi0504** [comment]
Hmm ... I am not sure about that. I think we can't solve this in the short term. The contributors also tried to do this, see mdaines/viz.js#52. BTW, I include my update of this in PR #4.

**Comment by hsiaoyi0504** [comment]
Maybe an approach to solve this is to use [this](https://github.com/webpack-contrib/compression-webpack-plugin), but I didn't use that before.

**Comment by hsiaoyi0504** [comment]
After trying for a while, it seems that `.gz` compressed version of `bundle.js` can't work with github pages, but I think it should work fine if deployed onto heroku.
